# Generated by Django 2.2.4 on 2019-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_main_image', models.ImageField(null=True, upload_to='images/')),
                ('tour_name', models.CharField(max_length=255)),
                ('tour_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tour_duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tour_second_image', models.ImageField(null=True, upload_to='products_images/')),
                ('tour_description', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('day1_description', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('day2_description', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('day3_description', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('day4_description', models.TextField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
    ]
