# Generated by Django 2.2.4 on 2019-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_second_image',
            field=models.ImageField(null=True, upload_to='package_images/'),
        ),
    ]
