# Generated by Django 2.2.4 on 2019-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_auto_20190907_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_duration',
            field=models.CharField(max_length=255),
        ),
    ]
