# Generated by Django 2.2.4 on 2019-09-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_auto_20190907_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='day1_head',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='day2_head',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='day3_head',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='day4_head',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='day5_description',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='day5_head',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
