# Generated by Django 2.2.4 on 2019-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_auto_20190907_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_main_image',
            field=models.ImageField(null=True, upload_to='package_images/'),
        ),
    ]
