# Generated by Django 2.2.4 on 2019-09-17 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_auto_20190908_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_list_image', models.ImageField(null=True, upload_to='package_images/')),
                ('post_name', models.CharField(max_length=255)),
                ('post_description', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
