# Generated by Django 2.2.4 on 2019-09-18 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_post_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_detail_image', models.ImageField(null=True, upload_to='package_images/')),
                ('post_detail_name', models.CharField(max_length=255)),
                ('post_detail_description', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
