# Generated by Django 2.2.4 on 2019-09-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_post_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_detail',
        ),
        migrations.AddField(
            model_name='post_list',
            name='post_detail_description',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='post_detail_name',
            field=models.TextField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='post_name',
            field=models.TextField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
